### ISSUE TITLE
GitFetchStrategy wrongly interpreted as tarball

### ISSUE THREAD

**Issue by justintoo** [scalability-llnl/spack#12]
@tgamblin Installing ROSE on `aztec` works just fine, but something is different when I'm trying to install on my local tux machine:

```bash
$ spack install rose
==> Installing rose
==> boost is already installed in /export/tmp.too1/development/projects/rose/master/spack/opt/unknown_arch/gcc@4.4.7/boost@1.54.0.
==> autoconf is already installed in /export/tmp.too1/development/projects/rose/master/spack/opt/unknown_arch/gcc@4.4.7/autoconf@2.69.
==> libtool is already installed in /export/tmp.too1/development/projects/rose/master/spack/opt/unknown_arch/gcc@4.4.7/libtool@2.4.
==> jdk is already installed in /export/tmp.too1/development/projects/rose/master/spack/opt/unknown_arch/gcc@4.4.7/jdk@8u25-linux-x64.
==> automake is already installed in /export/tmp.too1/development/projects/rose/master/spack/opt/unknown_arch/gcc@4.4.7/automake@1.14-7dfae544.
==> rose-master.
Traceback (most recent call last):
  File "./bin/spack", line 105, in <module>
    command(parser, args)
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/cmd/install.py", line 62, in install
    ignore_deps=args.ignore_deps)
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 729, in do_install
    self.do_patch()
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 663, in do_patch
    self.do_stage()
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 645, in do_stage
    self.do_fetch()
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 633, in do_fetch
    self.stage.fetch()
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 457, in stage
    mirror_path=self.mirror_path(),
  File "/export/tmp.too1/development/projects/rose/master/spack/lib/spack/spack/package.py", line 482, in mirror_path
    filename += extension(self.url) if self.url else "tar.gz"
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

This is the Git version information in `rose/package.py`:

```python
version('master', branch='master', git='https://github.com/rose-compiler/edg4x-rose.git')
```

From what I can tell, it looks like Spack is interpreting this as a tarball rather than a Git repository. Your guidance is appreciated!

**Comment by tgamblin** [comment]
@justintoo: It looks like you're on the master branch, or at least not on the current develop branch.  Can you see if it works on develop?

**Comment by tgamblin** [comment]
@justintoo: ping

**Comment by justintoo** [comment]
@tgamblin thanks - I will try now with the latest Spack master. Please standby...

**Comment by justintoo** [comment]
It works just fine now @tgamblin. Thank you!
