### ISSUE TITLE
scipy fails to build on RHEL6

### ISSUE THREAD

**Issue by certik** [scalability-llnl/spack#33]
```
==> Trying to fetch from https://pypi.python.org/packages/source/s/scipy/scipy-0.15.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/certik/repos/spack/var/spack/stage/py-scipy@0.15.0%gcc@4.9.2=unknown_arch-ad579252/scipy-0.15.0.tar.gz
==> Created stage in /home/certik/repos/spack/var/spack/stage/py-scipy@0.15.0%gcc@4.9.2=unknown_arch-ad579252.
==> No patches needed for py-scipy.
==> Building py-scipy.
/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
lapack_opt_info:
openblas_lapack_info:
  libraries openblas not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

lapack_mkl_info:
mkl_info:
  libraries mkl,vml,guide not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib
  libraries lapack_atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
  libraries lapack_atlas not found in /usr/local/lib64
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
  libraries lapack_atlas not found in /usr/lib64/sse2
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib64
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
numpy.distutils.system_info.atlas_threads_info
  NOT AVAILABLE

atlas_info:
  libraries f77blas,cblas,atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib
  libraries lapack_atlas not found in /home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib
  libraries f77blas,cblas,atlas not found in /usr/local/lib64
  libraries lapack_atlas not found in /usr/local/lib64
  libraries f77blas,cblas,atlas not found in /usr/local/lib
  libraries lapack_atlas not found in /usr/local/lib
  libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
  libraries lapack_atlas not found in /usr/lib64/sse2
  libraries f77blas,cblas,atlas not found in /usr/lib64
  libraries lapack_atlas not found in /usr/lib64
  libraries f77blas,cblas,atlas not found in /usr/lib
  libraries lapack_atlas not found in /usr/lib
  libraries f77blas,cblas,atlas not found in /usr/lib/
  libraries lapack_atlas not found in /usr/lib/
numpy.distutils.system_info.atlas_info
  NOT AVAILABLE

/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1432: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
lapack_info:
  libraries lapack not found in ['/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1443: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
lapack_src_info:
  NOT AVAILABLE

/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/system_info.py:1446: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
  NOT AVAILABLE

Running from scipy source directory.
Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    setup_package()
  File "setup.py", line 246, in setup_package
    setup(**metadata)
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 173, in configuration
    config.add_subpackage('scipy')
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 16, in configuration
    config.add_subpackage('linalg')
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-numpy@1.9.1-cd0f8d9e/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/linalg/setup.py", line 18, in configuration
    raise NotFoundError('no lapack/blas resources found')
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
==> Error: command '/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/python@2.7.8-3cadb17a/bin/python setup.py install --prefix=/home/certik/repos/spack/opt/unknown_arch/gcc@4.9.2/py-scipy@0.15.0-ad579252' returned error code 1
```

**Comment by zorobaba** [comment]
Hi i have the same problem

**Comment by tgamblin** [comment]
This should be fixed on develop thanks to @lee218llnl.  Please reopen if not.
