### ISSUE TITLE
NameError: global name 'tty' is not defined

### ISSUE THREAD

**Issue by certik** [scalability-llnl/spack#35]
```
certik@redhawk:~/repos/spack/var/spack/packages(master)$ spack install
Traceback (most recent call last):
  File "/home/certik/bin/spack", line 135, in <module>
    main()
  File "/home/certik/bin/spack", line 109, in main
    return_val = command(parser, args)
  File "/home/certik/repos/spack/lib/spack/spack/cmd/install.py", line 55, in install
    tty.die("install requires at least one package argument")
NameError: global name 'tty' is not defined
```

**Comment by tgamblin** [comment]
This is fixed in develop by 203fd861.  Will be in next release.
